[package]
name = "uniffi-bindgen-cli"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
# Note: in the real-world you probably want this to be named `uniffi-bindgen`, but we can't do that
# in the UniFFI repository since we have a different binary named `uniffi-bindgen`
name = "uniffi-bindgen-cli"
path = "uniffi-bindgen.rs"

[dependencies]
uniffi = { workspace = true, features = ["cli"] }

[features]
ffi-trace = ["uniffi/ffi-trace"]
