[package]
name = "uniffi-bindgen-cli"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
uniffi = { workspace = true, features = ["cli"] }

[features]
ffi-trace = ["uniffi/ffi-trace"]
