[package]
name = "uniffi-bindgen-tests-external-types-source"
version = "0.31.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
thiserror = "1"
uniffi = { workspace = true }
