[package]
name = "uniffi_udl"
version = "0.25.1"
description = "udl parsing for the uniffi project"
documentation = "https://mozilla.github.io/uniffi-rs"
homepage = "https://mozilla.github.io/uniffi-rs"
repository = "https://github.com/mozilla/uniffi-rs"
license = "MPL-2.0"
edition = "2021"
keywords = ["ffi", "bindgen"]

[dependencies]
anyhow = "1"
weedle2 = { version = "4.0.0", path = "../weedle2" }
uniffi_meta = { path = "../uniffi_meta", version = "=0.25.1" }
uniffi_testing = { path = "../uniffi_testing", version = "=0.25.1" }
