[package]
name = "uniffi-example-todolist"
edition = "2021"
version = "0.22.0"
authors = ["Firefox Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
name = "uniffi_todolist"

[dependencies]
uniffi = {path = "../../uniffi"}
once_cell = "1.12"
thiserror = "1.0"

[build-dependencies]
uniffi_build = {path = "../../uniffi_build"}

[dev-dependencies]
uniffi_bindgen = {path = "../../uniffi_bindgen"}
uniffi_macros = {path = "../../uniffi_macros"}
