[package]
name = "uniffi_meta"
version = "0.19.3"
edition = "2021"
description = "uniffi_meta"
homepage = "https://mozilla.github.io/uniffi-rs"
repository = "https://github.com/mozilla/uniffi-rs"
license = "MPL-2.0"
keywords = ["ffi", "bindgen"]

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
