[package]
name = "uniffi_testing"
authors = ["Firefox Sync Team <sync-team@mozilla.com>"]
version = "0.19.2"
edition = "2021"
license = "MPL-2.0"
publish = false

[dependencies]
anyhow = "1"
camino = "1.0.8"
cargo_metadata = "0.14"
fs-err = "2.7.0"
lazy_static = "1.4"
serde = "1"
serde_json = "1"
