[package]
name = "uniffi_testing"
authors = ["Firefox Sync Team <sync-team@mozilla.com>"]
version = "0.21.1"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow = "1"
camino = "1.0.8"
cargo_metadata = "0.15"
fs-err = "2.7.0"
once_cell = "1.12"
serde = "1"
serde_json = "1"
