[package]
name = "uniffi-example-sprites"
edition = "2018"
version = "0.1.0"
authors = ["Firefox Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"

[lib]
crate-type = ["cdylib"]
name = "uniffi_sprites"

[dependencies]
uniffi_macros = {path = "../../uniffi_macros"}
uniffi = {path = "../../uniffi"}

[build-dependencies]
uniffi_build = {path = "../../uniffi_build"}
