[package]
name = "uniffi-example-geometry"
edition = "2021"
version = "0.22.0"
authors = ["Firefox Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
name = "uniffi_geometry"

[dependencies]
uniffi = {path = "../../uniffi"}

[build-dependencies]
uniffi_build = {path = "../../uniffi_build"}

[dev-dependencies]
uniffi_macros = {path = "../../uniffi_macros"}
uniffi_bindgen = {path = "../../uniffi_bindgen"}
