# Note that this `release.toml` exists to capture things that must only be
# done once for `cargo release-backend-crates`.
#
# [../uniffi/release.toml](../uniffi/release.toml) captures things that must only be done for `cargo release-uniffi`
#
# All other config exists in [../release.toml](../release.toml).

release = false
tag = false
