[package]
name = "uniffi-example-rondpoint"
edition = "2021"
version = "0.22.0"
license = "MPL-2.0"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
name = "uniffi_rondpoint"

[dependencies]
uniffi = { workspace = true, features = ["pointer-ffi"] }

[build-dependencies]
uniffi = { workspace = true, features = ["build", "pointer-ffi"] }

[dev-dependencies]
uniffi = { workspace = true, features = ["bindgen-tests"] }

[features]
ffi-trace = ["uniffi/ffi-trace"]
