[package]
name = "uniffi-example-rondpoint"
edition = "2018"
version = "0.1.0"
authors = ["Firefox Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"

[lib]
crate-type = ["cdylib"]
name = "uniffi_rondpoint"

[dependencies]
anyhow = "1.0"
log = "0.4"
ffi-support = "0.4"
lazy_static = "1.4"
uniffi = {path = "../../uniffi"}
uniffi_macros = {path = "../../uniffi_macros"}

[build-dependencies]
uniffi = {path = "../../uniffi"}
