[package]
name = "uniffi-example-rondpoint"
edition = "2021"
version = "0.22.0"
authors = ["Firefox Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
name = "uniffi_rondpoint"

[dependencies]
uniffi = {path = "../../uniffi", features=["builtin-bindgen"]}

[build-dependencies]
uniffi_build = {path = "../../uniffi_build", features=["builtin-bindgen"]}

[dev-dependencies]
uniffi_bindgen = {path = "../../uniffi_bindgen"}
uniffi_macros = {path = "../../uniffi_macros"}
