[package]
name = "uniffi-example-remote-types"
edition = "2021"
version = "0.22.0"
license = "MPL-2.0"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
name = "remote_types"

[dependencies]
anyhow = "1"
log = "0.4"
uniffi = { workspace = true }

[build-dependencies]
uniffi = { workspace = true, features = ["build", "pointer-ffi"] }

[dev-dependencies]
uniffi = { workspace = true, features = ["bindgen-tests"] }

[features]
ffi-trace = ["uniffi/ffi-trace"]
