[general]
# Directories to search for templates, relative to the crate root.
dirs = [ "src/templates", "src/bindings/kotlin/templates", "src/bindings/python/templates", "src/bindings/swift/templates", "src/bindings/gecko_js/templates", "src/bindings/ruby/templates" ]

[[syntax]]
name = "kt"

[[syntax]]
name = "py"

[[syntax]]
name = "swift"

[[syntax]]
name = "c"

[[syntax]]
name = "rs"

[[syntax]]
name = "webidl"

[[syntax]]
name = "xpidl"

[[syntax]]
name = "cpp"

[[syntax]]
name = "rb"
