[general]
# Directories to search for templates, relative to the crate root.
dirs = [
    "src/templates",
    "src/bindings/gecko_cpp/templates",
    "src/bindings/kotlin/templates",
    "src/bindings/python/templates",
    "src/bindings/swift/templates",
]

[[syntax]]
name = "kt"

[[syntax]]
name = "py"

[[syntax]]
name = "swift"

[[syntax]]
name = "c"

[[syntax]]
name = "rs"